<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Performance Management – Light Deck</title>
<style>
  :root{
    --bg: #fdf8ee;            /* light pastel yellow */
    --lilac: #ede9fe;         /* lilac block */
    --blue: #e0f2ff;          /* soft blue accent */
    --mint: #e8fff3;          /* mint accent */
    --ink: #263238;           /* dark text for contrast */
    --muted: #546e7a;
    --brand: #7c3aed;         /* purple */
    --brand-2:#3b82f6;        /* blue */
    --shadow: 0 10px 30px rgba(0,0,0,.08);
  }

  html, body { height:100%; margin:0; background: var(--bg); color: var(--ink); font-family: Inter, ui-sans-serif, system-ui, Segoe UI, Roboto, Arial, sans-serif; }
  /* Deck container */
  .deck { position:relative; height:100dvh; overflow:hidden; }
  /* Slide: occupies full viewport */
  .slide {
    position:absolute; inset:0; padding: clamp(16px, 5vw, 36px);
    display:grid; grid-template-rows:auto 1fr; gap: clamp(12px,2vh,20px);
    background:
      radial-gradient(900px 300px at -10% -10%, rgba(255,255,255,.9), transparent 60%),
      radial-gradient(900px 300px at 110% -10%, rgba(255,255,255,.9), transparent 60%),
      var(--bg);
    opacity:0; transform: translateX(40px); transition: opacity .4s ease, transform .4s ease;
  }
  .slide.active { opacity:1; transform: translateX(0); pointer-events:auto; }
  .slide.inactive { pointer-events:none; }
  .hdr { display:flex; align-items:center; gap:12px; }
  .badge { font-size:12px; padding:5px 10px; border-radius:999px; background:#fff8; border:1px solid rgba(0,0,0,.06); }
  h1, h2 { margin:0; }
  h1 { font-size: clamp(22px, 3.2vw, 34px); }
  h2 { font-size: clamp(18px, 2.6vw, 28px); }
  .grid { display:grid; gap: clamp(12px, 2vw, 18px); grid-template-columns: repeat(12, 1fr); height:100%; }
  .panel {
    background:#ffffffd9; backdrop-filter: blur(4px);
    border:1px solid rgba(0,0,0,.06); border-radius:16px; padding: clamp(12px,1.8vw,16px);
    box-shadow: var(--shadow);
  }
  .note {
    background: linear-gradient(180deg, #fff7ce, #fff1a6);
    border:1px dashed rgba(0,0,0,.18); border-radius:14px; padding:12px;
  }
  .callout {
    background: linear-gradient(180deg, var(--lilac), #f6f1ff);
    border:1px solid rgba(124,58,237,.25);
    border-radius:16px; padding:14px;
  }
  .imgbox {
    background: linear-gradient(180deg, #ffffff, #faf9ff);
    border:1px solid rgba(0,0,0,.06); border-radius:16px; overflow:hidden;
    display:flex; align-items:center; justify-content:center;
  }
  .imgbox img { width:100%; height:100%; object-fit:cover; }
  ul { margin:8px 0 0 18px; }

  /* Bottom navigation bar */
  .nav {
    position:fixed; bottom:0; left:0; right:0;
    background: linear-gradient(180deg, #ffffffcc, #ffffff); backdrop-filter: blur(6px);
    border-top:1px solid rgba(0,0,0,.08);
    display:flex; align-items:center; justify-content:space-between;
    padding:10px clamp(12px,4vw,24px); z-index:5;
  }
  .prog {
    height:10px; width:42vw; max-width:560px; min-width:160px;
    background:#f1f5f9; border-radius:999px; overflow:hidden; border:1px solid rgba(0,0,0,.06);
  }
  .bar { height:100%; width:0%; background: linear-gradient(90deg, var(--brand), var(--brand-2)); transition:width .3s ease; }
  .btn {
    border:0; padding:10px 14px; border-radius:12px; cursor:pointer; font-weight:600;
    color:white; background:linear-gradient(90deg, var(--brand), var(--brand-2)); box-shadow: 0 6px 16px rgba(123,58,237,.24);
  }
  .btn.ghost {
    color: var(--ink); background: #ffffff; border:1px solid rgba(0,0,0,.1); box-shadow:none;
  }
  .pct { font-size:13px; color: var(--muted); margin-left:10px; }

  /* Chips & micro tasks */
  .chips { display:flex; gap:8px; flex-wrap:wrap; }
  .chip { background:#fff; border:1px solid rgba(0,0,0,.08); padding:6px 10px; border-radius:999px; font-size:12px; }

  /* Quiz block */
  .quiz { background: linear-gradient(180deg, var(--blue), #f8fbff); border:1px solid rgba(59,130,246,.2);
          border-radius:18px; padding:14px; }
  .quiz h3 { margin:0 0 8px; }
  .choice { display:block; margin:6px 0; }
  .feedback { margin-top:8px; font-weight:600; }
  .ok { color:#1b7f32; }
  .bad { color:#b81e1e; }

  /* Responsive */
  @media (max-width: 900px){
    .grid { grid-template-columns: 1fr; }
  }
</style>
</head>
<body>

<div class="deck" id="deck">

  <!-- SLIDE 1: Opening -->
  <section class="slide active" data-id="s1">
    <div class="hdr">
      <span class="badge">Start</span>
      <h1>Performance Management, made engaging</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 7;">
        <h2>What this module delivers</h2>
        <ul>
          <li>Crystal‑clear overview of the PM cycle and why it matters 🎯</li>
          <li>Quick, visual frameworks: KPI vs OKR vs BARS 🔍</li>
          <li>Practical rituals for check‑ins, evidence, and calibration 🤝</li>
        </ul>
        <div class="chips" style="margin-top:10px;">
          <span class="chip">Light theme</span>
          <span class="chip">1‑slide at a time</span>
          <span class="chip">Micro‑tasks</span>
        </div>
        <div class="note" style="margin-top:12px;">Tip: Use the Next button below or press Arrow →</div>
      </div>
      <div class="imgbox" style="grid-column: span 5; min-height: 280px;">
        <img src="image.jpg" alt="Performance management" style="width:40; border-radius:4px;">
      </div>
    </div>
  </section>

  <!-- SLIDE 2: Cycle -->
  <section class="slide inactive" data-id="s2">
    <div class="hdr">
      <span class="badge">1/ The Cycle</span>
      <h1>Plan → Execute → Review → Reward → Develop</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 7;">
        <h2>The operating rhythm</h2>
        <ul>
          <li><b>Plan</b>: SMART goals, role expectations, aligned OKRs.</li>
          <li><b>Execute</b>: monthly 1:1s, coaching, capture evidence.</li>
          <li><b>Review</b>: mid‑year/year‑end; synthesize outcomes + behaviors.</li>
          <li><b>Calibrate</b>: align standards and mitigate bias.</li>
          <li><b>Reward & Develop</b>: ratings, pay, recognition, growth plans.</li>
        </ul>
        <div class="callout" style="margin-top:10px;">Micro‑task: Write one sentence describing how check‑ins help avoid “recency bias”.</div>
      </div>
      <div class="imgbox" style="grid-column: span 5; min-height: 300px; background: var(--lilac);">
        <img src="image.jpg" alt="Cycle graphic">
      </div>
    </div>
  </section>

  <!-- SLIDE 3: Frameworks -->
  <section class="slide inactive" data-id="s3">
    <div class="hdr">
      <span class="badge">2/ Frameworks</span>
      <h1>KPIs, OKRs, and BARS—who does what?</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 4;">
        <h2>KPI = Health</h2>
        <p>Steady‑state measures of critical outcomes or processes.</p>
        <ul>
          <li>Lagging indicators; thresholds & targets.</li>
          <li>Examples: NPS, cycle time, on‑time reviews.</li>
        </ul>
        <img src="image.jpg" alt="KPI visual" style="width:100%; margin-top:8px; border-radius:12px;">
      </div>
      <div class="panel" style="grid-column: span 4; background: var(--blue);">
        <h2>OKR = Change</h2>
        <p>Time‑boxed priorities that stretch capability.</p>
        <ul>
          <li>Objective (qualitative) + 2–4 Key Results (quantitative).</li>
          <li>Score 0.0–1.0 or traffic‑light.</li>
        </ul>
        <img src="image.jpg" alt="OKR visual" style="width:100%; margin-top:8px; border-radius:12px;">
      </div>
      <div class="panel" style="grid-column: span 4; background: var(--mint);">
        <h2>BARS = Behavior</h2>
        <p>Behaviorally Anchored Rating Scales with concrete examples.</p>
        <ul>
          <li>Improves rater reliability; clearer coaching.</li>
          <li>Use for core competencies.</li>
        </ul>
        <img src="image.jpg" alt="BARS visual" style="width:100%; margin-top:8px; border-radius:12px;">
      </div>
    </div>
  </section>

  <!-- SLIDE 4: Quiz A -->
  <section class="slide inactive" data-id="s4">
    <div class="hdr">
      <span class="badge">Checkpoint A</span>
      <h1>Quick knowledge check</h1>
    </div>
    <div class="grid">
      <div class="quiz panel" style="grid-column: span 7;">
        <h3>Which pairing is most accurate?</h3>
        <label class="choice"><input type="radio" name="qa1" value="a"> KPI → stretch change; OKR → steady health</label>
        <label class="choice"><input type="radio" name="qa1" value="b"> KPI → process health; OKR → time‑bound change</label>
        <label class="choice"><input type="radio" name="qa1" value="c"> BARS → numeric throughput metric</label>
        <div style="margin-top:8px;">
          <button class="btn" onclick="check('qa1','b','fb1')">Submit</button>
          <button class="btn ghost" onclick="resetChoice('qa1','fb1')">Reset</button>
        </div>
        <div class="feedback" id="fb1"></div>
      </div>
      <div class="panel" style="grid-column: span 5;">
        <h2>Why this matters</h2>
        <p>Clarity prevents “metric soup.” Use OKRs to move the needle; monitor KPIs to stay healthy; use BARS to shape behavior.</p>
      </div>
    </div>
  </section>

  <!-- SLIDE 5: Goals -->
  <section class="slide inactive" data-id="s5">
    <div class="hdr">
      <span class="badge">3/ Goals</span>
      <h1>Write goals people can actually execute</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 7;">
        <h2>SMART but specific</h2>
        <ul>
          <li>Specific: narrow the scope and verb.</li>
          <li>Measurable: number + baseline + data source.</li>
          <li>Achievable & Relevant: realistic stretch, linked to strategy.</li>
          <li>Time‑bound: due date and check‑in cadence.</li>
        </ul>
        <div class="note" style="margin-top:10px;">Micro‑task: Rewrite “Improve engagement” into one SMART objective with a metric and date.</div>
      </div>
      <div class="imgbox" style="grid-column: span 5;">
        <img src="image.jpg" alt="Goals illustration">
      </div>
    </div>
  </section>

  <!-- SLIDE 6: Feedback -->
  <section class="slide inactive" data-id="s6">
    <div class="hdr">
      <span class="badge">4/ Feedback</span>
      <h1>Coaching rituals that stick</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 6;">
        <h2>Cadence</h2>
        <ul>
          <li>Monthly 1:1s: goals, blockers, wins, learning.</li>
          <li>Capture artifacts to reduce recency bias.</li>
          <li>Agree actions with owners and dates.</li>
        </ul>
      </div>
      <div class="panel" style="grid-column: span 6; background: var(--lilac);">
        <h2>Say it with SBI ✍️</h2>
        <ul>
          <li>Situation: “Yesterday’s client review…”</li>
          <li>Behavior: “…you summarized decisions clearly…”</li>
          <li>Impact: “…which kept us on time.”</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- SLIDE 7: Ratings & Calibration -->
  <section class="slide inactive" data-id="s7">
    <div class="hdr">
      <span class="badge">5/ Fairness</span>
      <h1>Ratings and calibration done right</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 6;">
        <h2>Inputs</h2>
        <ul>
          <li>Results: KPI & OKR evidence.</li>
          <li>Behaviors: BARS descriptors and examples.</li>
          <li>Context: role scope and span of control.</li>
        </ul>
      </div>
      <div class="panel" style="grid-column: span 6; background: var(--blue);">
        <h2>Calibration tips</h2>
        <ul>
          <li>Common rubric; challenge outliers with data.</li>
          <li>Bias checks: recency, halo/horns, leniency, affinity.</li>
          <li>Document rationale and message clearly.</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- SLIDE 8: Quiz B -->
  <section class="slide inactive" data-id="s8">
    <div class="hdr">
      <span class="badge">Checkpoint B</span>
      <h1>One more quick check</h1>
    </div>
    <div class="grid">
      <div class="quiz panel" style="grid-column: span 7;">
        <h3>Primary purpose of calibration?</h3>
        <label class="choice"><input type="radio" name="qb1" value="a"> Enforce forced distribution</label>
        <label class="choice"><input type="radio" name="qb1" value="b"> Align ratings standards and ensure fairness</label>
        <label class="choice"><input type="radio" name="qb1" value="c"> Avoid documentation</label>
        <div style="margin-top:8px;">
          <button class="btn" onclick="check('qb1','b','fb2')">Submit</button>
          <button class="btn ghost" onclick="resetChoice('qb1','fb2')">Reset</button>
        </div>
        <div class="feedback" id="fb2"></div>
      </div>
      <div class="panel" style="grid-column: span 5;">
        <h2>Pro tip</h2>
        <p>Run pre‑calibration hygiene: ensure each case has evidence, context, and draft rationale before the live discussion.</p>
      </div>
    </div>
  </section>

  <!-- SLIDE 9: Wrap -->
  <section class="slide inactive" data-id="s9">
    <div class="hdr">
      <span class="badge">Finish</span>
      <h1>Wrap‑up & next steps</h1>
    </div>
    <div class="grid">
      <div class="panel" style="grid-column: span 7;">
        <h2>Do this this month</h2>
        <ul>
          <li>Draft 1 Objective + 2–3 KRs; share for alignment.</li>
          <li>Set a recurring monthly 1:1 with a simple agenda.</li>
          <li>Create a 4‑level BARS for one core competency.</li>
        </ul>
        <div class="chips" style="margin-top:10px;">
          <span class="chip">Template exported</span>
          <span class="chip">Progress saved</span>
        </div>
      </div>
      <div class="imgbox" style="grid-column: span 5;">
        <img src="image.jpg" alt="Wrap illustration">
      </div>
    </div>
  </section>

</div>

<!-- Bottom navigation -->
<div class="nav">
  <div style="display:flex; align-items:center; gap:10px;">
    <button class="btn ghost" id="btnPrev">← Back</button>
    <button class="btn" id="btnNext">Next →</button>
  </div>
  <div style="display:flex; align-items:center;">
    <div class="prog"><div class="bar" id="bar"></div></div>
    <div class="pct" id="pct">Slide 1/9</div>
  </div>
  <div style="font-size:12px; color:var(--muted);">Press ← → to navigate</div>
</div>

<script>
  const slides = Array.from(document.querySelectorAll('.slide'));
  const total = slides.length;
  const bar = document.getElementById('bar');
  const pct = document.getElementById('pct');
  const prev = document.getElementById('btnPrev');
  const next = document.getElementById('btnNext');
  const key = 'pm_lightdeck_idx_v1';

  let idx = load() ?? 0;
  show(idx, false);

  function show(i, animate=true){
    slides.forEach((s, k)=>{
      s.classList.toggle('active', k===i);
      s.classList.toggle('inactive', k!==i);
      if(animate){ s.style.transitionDelay = (k===i)?'0s': '0s'; }
    });
    const p = Math.round(((i+1)/total)*100);
    bar.style.width = p+'%';
    pct.textContent = `Slide ${i+1}/${total}`;
    prev.disabled = (i===0);
    next.textContent = (i===total-1) ? 'Finish' : 'Next →';
    save(i);
  }
  function save(i){ try{ localStorage.setItem(key, String(i)); }catch(e){} }
  function load(){ try{ const v = localStorage.getItem(key); return v? parseInt(v): null; }catch(e){ return null; } }

  prev.addEventListener('click', ()=>{ if(idx>0){ idx--; show(idx); } });
  next.addEventListener('click', ()=>{
    if(idx < total-1){ idx++; show(idx); }
    else { alert('Module complete! You can review slides or close the window.'); }
  });
  window.addEventListener('keydown', (e)=>{
    if(e.key==='ArrowRight'){ next.click(); }
    if(e.key==='ArrowLeft'){ prev.click(); }
  });

  // Quiz helpers
  function check(name, correct, fbId){
    const sel = document.querySelector('input[name="'+name+'"]:checked');
    const fb = document.getElementById(fbId);
    if(!sel){ fb.innerHTML = '<span class="bad">Please select an option.</span>'; return; }
    if(sel.value===correct){ fb.innerHTML = '<span class="ok">Correct!</span>'; }
    else { fb.innerHTML = '<span class="bad">Not quite—peek back and try again.</span>'; }
  }
  function resetChoice(name, fbId){
    document.querySelectorAll('input[name="'+name+'"]').forEach(el=> el.checked=false);
    document.getElementById(fbId).innerHTML = '';
  }
</script>
</body>
</html>
